### ISSUE TITLE
You should delete this.

### ISSUE THREAD

**Issue by ViviNoSmol** [mttomaz/tlauncher-arch#1]
I don't know if you are still active (I don't think) But if you are seeing this (or someone is seeing this) You should not download this Tlauncher, not only is it confirmed that it is a virus regardless of the platform, but that it is made by a Russian company with anti-consumer and horrible practices. I recommend that you install the original TLauncher made by Artur Khusainov (Also known as TL-Legacy) and they are in the Aur and Flathub repositories. Please don't download malware, and don't download TLauncher.org.

**Comment by 1RaY-1** [comment]
I heard that too, that it is a virus.

**Comment by 0x241F31** [comment]
I used this launcher for years without problems. Any proofs that this is malware?

**Comment by 0x241F31** [comment]
Even it's original one TLauncher, not the "new" one which considered to be malicious

**Comment by A7mooz** [comment]
I inspected the script which you also could do before claiming this and it just builds TL from https://tlauncher.org/jar using wget so it's safe.

**Comment by Jerin-004** [comment]
yup it's definitely a virus

**Comment by a000011** [comment]
это что, второй контрнаступ хохлов?

**Comment by mttomaz** [comment]
I've added a warning at the README about this.

**Comment by BeanDx** [comment]
> это что, второй контрнаступ хохлов?

Stupid son of a bitch
